### PR TITLE
failed test

### PR DESCRIPTION
**Pull request by tyv**
hi, this is supposed to be handled, I can spend some time to see where it fails, but probably you'd see it much faster. 
Ping me if you need help with this.

### CODE REVIEW

**Comment by tyv** [comment]
this cases could be covered only with this: `'path/anyjs/**/*.**, 'path/anyjs/**/*.**/**',`

**Comment by es128** [comment]
The wording you used for the test case does not match the assertions. Did you intend to `assert.equal(false, ...`?

The current behavior is correct. Globs ignore dotfiles by default.

```js
> anymatch('path/anyjs/**/*.js', 'path/anyjs/dashed-name/.dotted-name/file.js')
false
> anymatch('path/anyjs/**/*.js', 'path/anyjs/dashed-name/.dotted-name2')
false
```

**Comment by tyv** [comment]
this tests are failing.
I assume if you use this matcher: `path/**` that means that `/path/fol-der/.folder/file` will return true, isn't it true?

**Comment by es128** [comment]
No, it's not true. Wildcard characters in [globs don't match dotfiles](https://github.com/isaacs/node-glob#dots).

If you want to be able to pass custom non-default options into the globbing lib through anymatch like `dot: true`, you could make a feature request or PR for that.

**Comment by tyv** [comment]
okay, I see thanks

**Pull request closed without merging**
